name: pyrobyte_test
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.2.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  provider: 6.1.1
  countup: 0.1.4
  wave: 0.2.2

  cupertino_icons: 1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: 2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/images/

  fonts:
    - family: Roboto-Light
      fonts:
        - asset: assets/fonts/Roboto-Light.ttf
    - family: Roboto-Regular
      fonts:
        - asset: assets/fonts/Roboto-Regular.ttf
    - family: Roboto-Medium
      fonts:
        - asset: assets/fonts/Roboto-Medium.ttf
    - family: Roboto-Bold
      fonts:
        - asset: assets/fonts/Roboto-Bold.ttf
    - family: Jost-Light
      fonts:
        - asset: assets/fonts/Jost-Light.ttf
    - family: Jost-Regular
      fonts:
        - asset: assets/fonts/Jost-Regular.ttf
    - family: Jost-Medium
      fonts:
        - asset: assets/fonts/Jost-Medium.ttf
    - family: Jost-Bold
      fonts:
        - asset: assets/fonts/Jost-Bold.ttf
        

 